- name: Kubernetes
  hosts: "worker-*"
  become: true

  tasks:
    - name: Copy certificates for worker
      copy:
        src: "../{{ item }}"
        dest: ~/
      loop:
        - "ca.pem"
        - "{{ ansible_host }}-key.pem"
        - "{{ ansible_host }}.pem"
