- name: Worker setup
  hosts: "worker-*"
  become: true

  tasks:
    - name: Copy certificates and configs for workers
      copy:
        src: "../{{ item }}"
        dest: ~/
      loop:
        - "ca.pem"
        - "{{ ansible_hostname }}-key.pem"
        - "{{ ansible_hostname }}.pem"
        - "{{ ansible_hostname }}.kubeconfig"
        - "kube-proxy.kubeconfig"

- name: Controller setup
  hosts: "controller-*"
  become: true
  
  tasks:
    - name: Create directory
      file:
        path: /var/lib/etcd/
        state: directory
    - name: Copy certificates for controllers
      copy:
        src: "../{{ item }}"
        dest: /etc/etcd/
      loop:
        - "ca.pem"
        - "ca-key.pem"
        - "kubernetes-key.pem"
        - "kubernetes.pem"
    - name: Copy etcd service config
      template:
        src: etcd.service.j2
        dest: /etc/systemd/system/etcd.service
    - name: Copy certificates and configs for controllers
      copy:
        src: "../{{ item }}"
        dest: ~/
      loop:
        - "service-account-key.pem"
        - "service-account.pem"
        - "admin.kubeconfig"
        - "kube-controller-manager.kubeconfig"
        - "kube-scheduler.kubeconfig"
    - name: Copy encryption config
      template:
        src: encryption-config.yml.j2
        dest: ~/encryption-config.yml
    - name: Install etcd
      unarchive:
        src: https://github.com/coreos/etcd/releases/download/v3.3.9/etcd-v3.3.9-linux-amd64.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Launch etcd
      systemd:
        name: etcd
        daemon_reload: yes
        enabled: yes
        state: started
