{
 "title": "Docker metrics by telegraf",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_n_containers" }
   ]
  },
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_n_containers_running" }
   ]
  },
  {
   "title": "Paused containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_n_containers_paused" }
   ]
  },
  {
   "title": "Stopped containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_n_containers_stopped" }
   ]
  },
  {
   "title": "Total MEM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "docker_memory_total/(1024*1024)"
    }
   ]
  },
  {
   "title": "Images",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "docker_n_images" }
   ]
  },
  {
   "title": "Total cpu usage per container in 1m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_cpu_usage_total[1m])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Sended traffic in 1m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_net_tx_bytes[1m])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Total cpu usage in percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Recieved traffic in 1m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_net_rx_bytes[1m])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Mem usage per container in percent",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage_percent",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Mem usage per container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "docker_container_mem_usage", "legendFormat": "{{container_name}}" }
   ]
  }
 ]
}