---
- name: Install docker
  hosts: all
  become: true

  tasks:
    - name: Add apt https repo support and python
      apt:
        name: "{{ item }}"
      loop:
        - gnupg-curl
        - python-pip
      tags: install

    - name: Add apt key
      apt_key:
        keyserver: https://download.docker.com/linux/ubuntu/gpg
        id: 0EBFCD88
      tags: install

    - name: Add apt repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      tags: install

    - name: Install docker CE package
      apt:
        name: docker-ce
      tags: install

    - name: Install python docker module
      pip:
        name: docker
      tags: install
      
    - name: Create a container
      docker_container:
        name: reddit
        image: "igormelnikov/otus-reddit:1.0"
        network_mode: host
